apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: null
  generation: 1
  labels:
    run: ananas-db
  name: ananas-db
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/ananas-db
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ananas-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ananas-db
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: ananas
        - name: POSTGRES_PASSWORD
          value: wVYyVmIiYL
        - name: POSTGRES_DB
          value: ananas_production
        image: postgres
        imagePullPolicy: Always
        name: ananas-db
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ananas-db-data
status: {}
----
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ananas-db
  name: ananas-db
  selfLink: /api/v1/namespaces/services/ananas-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: ananas-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ananas-db-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
